apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "secure_password"
  MYSQL_DATABASE: "laravel_db"
  MYSQL_USER: "laravel_user"
  MYSQL_PASSWORD: "secure_password"

