apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: laravel-app-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: laravel
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: laravel-worker-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      role: worker

