apiVersion: v1
kind: Secret
metadata:
  name: laravel-app-secret
  namespace: default
type: Opaque
stringData:
  APP_NAME: "Laravel"
  APP_ENV: "production"
  APP_KEY: "base64:CHANGE_ME"
  APP_DEBUG: "false"
  LOG_CHANNEL: "stack"

  DB_CONNECTION: "mysql"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "laravel"
  DB_USERNAME: "root"
  DB_PASSWORD: "password"

  REDIS_CLIENT: "phpredis"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""

  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"
