apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-worker
  labels:
    app: laravel-app
    role: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
      role: worker
  template:
    metadata:
      labels:
        app: laravel-app
        role: worker
    spec:
      containers:
        - name: worker
          image: laravel-app-image:v3
          imagePullPolicy: IfNotPresent
          command:
            - "php"
            - "/var/www/artisan"
            - "queue:work"
            - "--sleep=3"
            - "--tries=3"
            - "--timeout=60"
            - "--queue=default"

          # imagePullPolicy: Never
          # ports:
          #   - containerPort: 9000
          envFrom:
            - secretRef:
                name: laravel-app-secret
            - secretRef:
                name: mysql-secret
            - secretRef:
                name: redis-secret
          # volumeMounts:
          #   - name: nginx-config
          #     mountPath: /var/www/.env
          #     subPath: .env
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        
