apiVersion: v1
kind: Secret
metadata:
  name: laravel-app-secret
  namespace: default
type: Opaque
stringData:
  APP_NAME: "Laravel"
  APP_ENV: "production"
  APP_KEY: "base64:DfyYWL4L0tf7n2UpBlgu6GWSiQ3ZUSJNJSjJCf0JpLY="
  APP_DEBUG: "false"
  # APP_URL: "https://yourapp.com"
  DB_USERNAME: "laravel_user"
  DB_PASSWORD: "secure_password"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "laravel_db"
  # LOG_CHANNEL: "stack"
  # CACHE_DRIVER: "redis"           # ← Use Redis for cache
  # SESSION_DRIVER: "redis"         # ← Use Redis for sessions
  # QUEUE_CONNECTION: "redis"       # ← Use Redis for queues
  # REDIS_HOST: "redis-service"  # ← Redis DNS
  # REDIS_PORT: "6379"
  # REDIS_PASSWORD: (from secret)
